### ISSUE TITLE
v5.0.0 is incompatible with ts-node

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/path-type#9]
I'm hitting a similar issue to https://github.com/TypeStrong/ts-node/issues/155#issuecomment-570120923 with `ava` and `ts-node` while importing this in one of the functions I'm testing.

If there's no fix feel free to close this. I figured I couldn't hurt to open and at least others will now be able to find this.

```
  Uncaught exception in test/app/graphql/resolvers/query/display.ts

  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/xo/code/unraid/api/node_modules/path-type/index.js
  require() of ES modules is not supported.
  require() of /Users/xo/code/unraid/api/node_modules/path-type/index.js from /Users/xo/code/unraid/api/app/core/modules/info/get-all-devices.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/xo/code/unraid/api/node_modules/path-type/package.json.


  › Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from node_modules/path-type/package.json.
  › Object.<anonymous> (app/core/modules/info/get-all-devices.ts:4:4)
  ```

**Comment by OnkelTem** [comment]
You have two options.

## Option 1

To get it working:

* Install node 14+
* Then set the `type` field to 'module' value in your `package.json`.
* Then go and update all your local imports throughout the sources from `import ... from 'file'` to `import ... from 'file.js'` 
   Yes, `.js`, even if it's a TypeScript file. Ludicrous? Sure, but better future always comes for a price.
* Go into your `tsconfig.json` and set `"module"` to `"ES2020"` (or similar) and `"moduleResolution"` to `"node"`.

Congratulations, now your `tsc` is ready. At least it should now build the code and run it. BUT.

Your `ts-node` is not going to support this shi...ft. Have a look at this thread: https://github.com/TypeStrong/ts-node/issues/1007 where people discuss how they suffer precisely with this new approach. 

But roughly don't run `ts-node something` and don't do `node --require ts-node/register something` as well. Instead please do `node --loader ts-node/esm something` and contemplate messages like: 

```
(node:1577583) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

Inconvenient? Maybe. But at least your know that you're on the bleeding edge of technologies and that you're making this world a better place, at least for Sindre Sorhus.

## Option 2

Just don't use this. Or downgrade to the previous version, when the author didn't harm this world that much with his righteous attempts to make it "better".

**Comment by dperetti** [comment]
Indeed, It has been months now. The world is not "better" and we're still losing hours of work time on this, without any satisfactory solution in the end. I respect and admire your work @sindresorhus , but this forced path to ESM is not cool.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

And see the working config here: https://github.com/sindresorhus/is/blob/main/tsconfig.json

**Comment by sindresorhus** [comment]
@dperetti No one is forcing you to upgrade to v5. v4 works perfectly well. You can continue using it until you're able to move to ESM.
